#!/usr/bin/env bash
# Pre-edit hook: block edits to auto-generated files
set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || FILE_PATH=""

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# Block edits to terraform-docs auto-generated README
if [[ "$FILE_PATH" == */terraform/scps/README.md ]]; then
  echo "Blocked: $FILE_PATH is auto-generated by terraform-docs. Do not modify directly." >&2
  exit 2
fi
