name: Terraform Plan

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-plan.yml'
      - '.github/actions/terraform-composite/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      TF_VAR_organization_id: ${{ vars.TF_VAR_organization_id }}
      TF_VAR_dev_ou_id: ${{ vars.TF_VAR_dev_ou_id }}
      TF_VAR_aws_region: ${{ vars.TF_VAR_aws_region }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Terraform Plan
        uses: ./.github/actions/terraform-composite
        with:
          terraform_command: plan
          working_directory: terraform/scps
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_region: us-east-1
